services:
  - type: web
    name: coolflames-game
    env: java
    region: oregon
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/flames-game-1.0-SNAPSHOT.jar
    healthCheckPath: /api/flames/results
    envVars:
      - key: JAVA_VERSION
        value: 11
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: flames-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: flames-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: flames-db
          property: password
      - key: PORT
        value: 8080

databases:
  - name: flames-db
    databaseName: coolflames
    user: flames_user
    plan: free
    region: oregon
    ipAllowList: [] 