services:
  - type: web
    name: coolflames-game
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/flames-game-1.0-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        fromDatabase:
          name: flames-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: flames-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: flames-db
          property: password
      - key: JAVA_VERSION
        value: 11
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: flames-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: flames-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: flames-db
          property: password

databases:
  - name: flames-db
    databaseName: coolflames
    user: flames_user
    plan: free
    ipAllowList: []
    envVars:
      - key: POSTGRES_DB
        value: coolflames
      - key: POSTGRES_USER
        value: flames_user
      - key: POSTGRES_PASSWORD
        generateValue: true 